/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NETRUNNER_pl (https://sketchfab.com/NETRUNNER_pl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-wing-star-wars-inspired-interceptor-free-33a3e25abcb74e389c34c49fbeeef19a
Title: T-WING Star Wars inspired interceptor - FREE
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/twing.glb"
  );

  console.log(nodes, materials);

  const groupRef = useRef();

  // useFrame(({clock, camera}) => {

    // groupRef.current.position.y += Math.sin(clock.getElapsedTime());
    // groupRef.current.position.x += Math.cos(clock.getElapsedTime());

    // const { x, y, z } = groupRef.current.position;
    // camera.position.set(0, 0, z -10);
    // camera.lookAt(x,0,0);


  // });

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group position={[0, 0.38, 7.18]} scale={[1, 1.351, 0.787]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["T-wing"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["glow.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["glow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.steel}
        />
      </group>
      <group position={[0, 4.949, 7.863]} scale={[0.251, 0.251, 0.291]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.glow}
        />
      </group>
      <group position={[0, 6.72, 18.285]} scale={1.118}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.steel}
        />
      </group>
      <group
        position={[-17.742, 1.112, 2.518]}
        rotation={[0.072, 0.059, -0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.glow}
        />
      </group>
      <group position={[-1.044, 5.551, 14.384]} scale={1.784}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.steel}
        />
        <group position={[0.585, -3.112, -8.197]} scale={[0.561, 0.561, 0.649]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.steel}
            position={[-0.74, 5.093, 7.315]}
            scale={[1, 1, 0.864]}
          />
        </group>
      </group>
      <group position={[-1.884, 2.971, 14.605]} scale={[0.826, 1, 3.809]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials["T-wing"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_35.geometry}
          material={materials.steel}
        />
      </group>
      <group position={[-0.124, 5.369, 9.835]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials["glow.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials["glow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.glow}
        />
      </group>
      <group position={[0.001, 4.067, 10.299]} scale={[0.383, 0.225, 0.282]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.glow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials["glow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials["glow.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials.steel}
          position={[-0.002, 3.323, 1.213]}
          rotation={[-0.275, 0, 0]}
          scale={[1.773, 2.974, 2.456]}
        />
      </group>
      <group position={[0, 5.334, 9.88]} scale={[0.192, 0.231, 0.192]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.steel}
        />
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.581, 0.581, 0.484]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_59.geometry}
            material={materials.silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.glow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_61.geometry}
            material={materials["glow.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.steel}
          />
        </group>
      </group>
      <group
        position={[-0.004, 5.748, 14.363]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.062}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials.steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials["glow.003"]}
        />
        <group
          position={[0, 3.754, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.933}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_67.geometry}
            material={materials.silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_68.geometry}
            material={materials.glow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_69.geometry}
            material={materials.steel}
          />
        </group>
      </group>
      <group
        position={[0.021, 2.788, 20.987]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.534}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_75.geometry}
          material={materials["silver.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_77.geometry}
          material={materials["black_matte.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_78.geometry}
          material={materials.metal}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["t-wing_hull"]}
        position={[0, 0, -0.239]}
        scale={[1, 1, 1.157]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.steel}
        position={[0, -0.637, -5.068]}
        scale={[1.743, 0.039, 0.195]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.steel}
        position={[-17.84, 0.38, -6.981]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1.157, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.material_0}
        position={[-1.805, 2.526, -0.077]}
        rotation={[0, 0, 1.479]}
        scale={[0.73, 0.73, 0.455]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.steel}
        position={[-0.969, 3.029, 21.293]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.black_matte}
        position={[0, 0, -0.239]}
        scale={[1, 1, 1.157]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.silver}
        position={[0.004, 4.13, 11.469]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.511, 0.423, 0.423]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.black_matte}
        position={[-0.002, 3.959, 14.586]}
        rotation={[0.486, 0, 0]}
        scale={0.095}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_71.geometry}
        material={materials["glow.002"]}
        position={[0.114, 0.344, 17.732]}
        scale={[1.169, 1, 3.378]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_73.geometry}
        material={materials["glow.001"]}
        position={[-0.037, 0.382, 20.631]}
        scale={[2.559, 2.189, 5.751]}
      />
    </group>
  );
}

useGLTF.preload("/twing.glb");
